name: 'red-cat-pictures-dev'
services:
  app:
    build:
      context: .
      args:
        SITE_URL: http://localhost:4300
        CDN_URL: http://localhost:3500
    restart: on-failure:3
    env_file:
      - .env.prod
    volumes:
      - data:/app/.data
    ports:
      - 4400:3000

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.data
