services:
  cloudreve:
    image: cloudreve/cloudreve:4.17.0@sha256:5a73890b7fc35c5de76ed35a5901e9ae1d199e8a33a88eb9d31615505d93e3c4
    env_file:
      - .env
    volumes:
      - backend-data:/cloudreve/data
    networks:
      - internal
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:5212 || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
    restart: 'on-failure:3'
    deploy:
      resources:
        limits:
          cpus: '1'

  postgres:
    image: postgres:17@sha256:67f41722b7a8cbdb868a44a4995c846eddfdc2973bccb291ce937dce88ad5675
    env_file:
      - .env
    volumes:
      - database-postgres:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: 'on-failure:3'

  redis:
    image: redis:latest@sha256:298e5b3bc566bade82f46ad5511777a4a07a294097ce16ada2f6a42be5239df5
    volumes:
      - redis-data:/data
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 30s
      timeout: 5s
      retries: 3
    restart: 'on-failure:3'

volumes:
  backend-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/cloudreve-rcp/data
  database-postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/cloudreve-rcp/postgres
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/cloudreve-rcp/redis

networks:
  internal:
    driver: bridge
