version: '3.9'
services:
  app:
    image: ghcr.io/red-cat-pictures/red-cat-pictures:latest@sha256:e8efde19dff9f64b55433458000cf2e19d3a0aadbfeed4a4a6536cad1eb25ea5
    env_file:
      - .env
    volumes:
      - red-cat-pictures_data:/app/.data
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:3000/api/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  red-cat-pictures_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/red-cat-pictures/.data

networks:
  internal:
    driver: overlay
